server:
  port: 8085

spring:
  application:
    name: configs-server-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/haryagustian/microservices-external-config
          clone-on-start: true